//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace AdegaSOA.bpel4 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PedidoBinding", Namespace="http://xmlns.oracle.com/Pedido")]
    public partial class Pedido : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Pedido() {
            this.Url = global::AdegaSOA.Properties.Settings.Default.AdegaSOA_bpel4_Pedido;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event processCompletedEventHandler processCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("process", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PedidoProcessResponse", Namespace="http://xmlns.oracle.com/Pedido")]
        public PedidoProcessResponse process([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xmlns.oracle.com/Pedido")] PedidoProcessRequest PedidoProcessRequest) {
            object[] results = this.Invoke("process", new object[] {
                        PedidoProcessRequest});
            return ((PedidoProcessResponse)(results[0]));
        }
        
        /// <remarks/>
        public void processAsync(PedidoProcessRequest PedidoProcessRequest) {
            this.processAsync(PedidoProcessRequest, null);
        }
        
        /// <remarks/>
        public void processAsync(PedidoProcessRequest PedidoProcessRequest, object userState) {
            if ((this.processOperationCompleted == null)) {
                this.processOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessOperationCompleted);
            }
            this.InvokeAsync("process", new object[] {
                        PedidoProcessRequest}, this.processOperationCompleted, userState);
        }
        
        private void OnprocessOperationCompleted(object arg) {
            if ((this.processCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processCompleted(this, new processCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Pedido")]
    public partial class PedidoProcessRequest {
        
        private PedidoProcessRequestVinho[] vinhosField;
        
        private string cnpjField;
        
        private string senhaField;
        
        private string cpfField;
        
        private string nomePFField;
        
        private string cartaoPFField;
        
        private string enderecoPFField;
        
        private int qtdeTotalVinhoField;
        
        private double valorTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("vinho", IsNullable=false)]
        public PedidoProcessRequestVinho[] vinhos {
            get {
                return this.vinhosField;
            }
            set {
                this.vinhosField = value;
            }
        }
        
        /// <remarks/>
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string nomePF {
            get {
                return this.nomePFField;
            }
            set {
                this.nomePFField = value;
            }
        }
        
        /// <remarks/>
        public string cartaoPF {
            get {
                return this.cartaoPFField;
            }
            set {
                this.cartaoPFField = value;
            }
        }
        
        /// <remarks/>
        public string enderecoPF {
            get {
                return this.enderecoPFField;
            }
            set {
                this.enderecoPFField = value;
            }
        }
        
        /// <remarks/>
        public int qtdeTotalVinho {
            get {
                return this.qtdeTotalVinhoField;
            }
            set {
                this.qtdeTotalVinhoField = value;
            }
        }
        
        /// <remarks/>
        public double valorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Pedido")]
    public partial class PedidoProcessRequestVinho {
        
        private int vinhoIdField;
        
        private int qtdeField;
        
        /// <remarks/>
        public int vinhoId {
            get {
                return this.vinhoIdField;
            }
            set {
                this.vinhoIdField = value;
            }
        }
        
        /// <remarks/>
        public int qtde {
            get {
                return this.qtdeField;
            }
            set {
                this.qtdeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Pedido")]
    public partial class PedidoProcessResponse {
        
        private string resultField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void processCompletedEventHandler(object sender, processCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PedidoProcessResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PedidoProcessResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591