//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace AdegaSOA.localhost1 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EstoqueSoap", Namespace="http://ipt.br/soa")]
    public partial class Estoque : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarEstoqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarEstoqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarDemandaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitarReposicaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarArquivoXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarDataEntregaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarStatusPedidoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Estoque() {
            this.Url = global::AdegaSOA.Properties.Settings.Default.AdegaSOA_localhost1_Estoque;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarEstoqueCompletedEventHandler ListarEstoqueCompleted;
        
        /// <remarks/>
        public event VerificarEstoqueCompletedEventHandler VerificarEstoqueCompleted;
        
        /// <remarks/>
        public event VerificarDemandaCompletedEventHandler VerificarDemandaCompleted;
        
        /// <remarks/>
        public event SolicitarReposicaoCompletedEventHandler SolicitarReposicaoCompleted;
        
        /// <remarks/>
        public event EnviarArquivoXmlCompletedEventHandler EnviarArquivoXmlCompleted;
        
        /// <remarks/>
        public event VerificarDataEntregaCompletedEventHandler VerificarDataEntregaCompleted;
        
        /// <remarks/>
        public event AtualizarStatusPedidoCompletedEventHandler AtualizarStatusPedidoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/ListarEstoque", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vinho[] ListarEstoque() {
            object[] results = this.Invoke("ListarEstoque", new object[0]);
            return ((Vinho[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarEstoqueAsync() {
            this.ListarEstoqueAsync(null);
        }
        
        /// <remarks/>
        public void ListarEstoqueAsync(object userState) {
            if ((this.ListarEstoqueOperationCompleted == null)) {
                this.ListarEstoqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEstoqueOperationCompleted);
            }
            this.InvokeAsync("ListarEstoque", new object[0], this.ListarEstoqueOperationCompleted, userState);
        }
        
        private void OnListarEstoqueOperationCompleted(object arg) {
            if ((this.ListarEstoqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEstoqueCompleted(this, new ListarEstoqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/VerificarEstoque", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Reposicao[] VerificarEstoque() {
            object[] results = this.Invoke("VerificarEstoque", new object[0]);
            return ((Reposicao[])(results[0]));
        }
        
        /// <remarks/>
        public void VerificarEstoqueAsync() {
            this.VerificarEstoqueAsync(null);
        }
        
        /// <remarks/>
        public void VerificarEstoqueAsync(object userState) {
            if ((this.VerificarEstoqueOperationCompleted == null)) {
                this.VerificarEstoqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarEstoqueOperationCompleted);
            }
            this.InvokeAsync("VerificarEstoque", new object[0], this.VerificarEstoqueOperationCompleted, userState);
        }
        
        private void OnVerificarEstoqueOperationCompleted(object arg) {
            if ((this.VerificarEstoqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarEstoqueCompleted(this, new VerificarEstoqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/VerificarDemanda", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Reposicao[] VerificarDemanda(Reposicao[] listaReposicao) {
            object[] results = this.Invoke("VerificarDemanda", new object[] {
                        listaReposicao});
            return ((Reposicao[])(results[0]));
        }
        
        /// <remarks/>
        public void VerificarDemandaAsync(Reposicao[] listaReposicao) {
            this.VerificarDemandaAsync(listaReposicao, null);
        }
        
        /// <remarks/>
        public void VerificarDemandaAsync(Reposicao[] listaReposicao, object userState) {
            if ((this.VerificarDemandaOperationCompleted == null)) {
                this.VerificarDemandaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarDemandaOperationCompleted);
            }
            this.InvokeAsync("VerificarDemanda", new object[] {
                        listaReposicao}, this.VerificarDemandaOperationCompleted, userState);
        }
        
        private void OnVerificarDemandaOperationCompleted(object arg) {
            if ((this.VerificarDemandaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarDemandaCompleted(this, new VerificarDemandaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/SolicitarReposicao", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Reposicao[] SolicitarReposicao(Reposicao[] listaReposicao) {
            object[] results = this.Invoke("SolicitarReposicao", new object[] {
                        listaReposicao});
            return ((Reposicao[])(results[0]));
        }
        
        /// <remarks/>
        public void SolicitarReposicaoAsync(Reposicao[] listaReposicao) {
            this.SolicitarReposicaoAsync(listaReposicao, null);
        }
        
        /// <remarks/>
        public void SolicitarReposicaoAsync(Reposicao[] listaReposicao, object userState) {
            if ((this.SolicitarReposicaoOperationCompleted == null)) {
                this.SolicitarReposicaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitarReposicaoOperationCompleted);
            }
            this.InvokeAsync("SolicitarReposicao", new object[] {
                        listaReposicao}, this.SolicitarReposicaoOperationCompleted, userState);
        }
        
        private void OnSolicitarReposicaoOperationCompleted(object arg) {
            if ((this.SolicitarReposicaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitarReposicaoCompleted(this, new SolicitarReposicaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/EnviarArquivoXml", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviarArquivoXml(Reposicao[] listaReposicao) {
            this.Invoke("EnviarArquivoXml", new object[] {
                        listaReposicao});
        }
        
        /// <remarks/>
        public void EnviarArquivoXmlAsync(Reposicao[] listaReposicao) {
            this.EnviarArquivoXmlAsync(listaReposicao, null);
        }
        
        /// <remarks/>
        public void EnviarArquivoXmlAsync(Reposicao[] listaReposicao, object userState) {
            if ((this.EnviarArquivoXmlOperationCompleted == null)) {
                this.EnviarArquivoXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarArquivoXmlOperationCompleted);
            }
            this.InvokeAsync("EnviarArquivoXml", new object[] {
                        listaReposicao}, this.EnviarArquivoXmlOperationCompleted, userState);
        }
        
        private void OnEnviarArquivoXmlOperationCompleted(object arg) {
            if ((this.EnviarArquivoXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarArquivoXmlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/VerificarDataEntrega", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void VerificarDataEntrega() {
            this.Invoke("VerificarDataEntrega", new object[0]);
        }
        
        /// <remarks/>
        public void VerificarDataEntregaAsync() {
            this.VerificarDataEntregaAsync(null);
        }
        
        /// <remarks/>
        public void VerificarDataEntregaAsync(object userState) {
            if ((this.VerificarDataEntregaOperationCompleted == null)) {
                this.VerificarDataEntregaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarDataEntregaOperationCompleted);
            }
            this.InvokeAsync("VerificarDataEntrega", new object[0], this.VerificarDataEntregaOperationCompleted, userState);
        }
        
        private void OnVerificarDataEntregaOperationCompleted(object arg) {
            if ((this.VerificarDataEntregaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarDataEntregaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/AtualizarStatusPedido", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AtualizarStatusPedido(Pedido pedido) {
            this.Invoke("AtualizarStatusPedido", new object[] {
                        pedido});
        }
        
        /// <remarks/>
        public void AtualizarStatusPedidoAsync(Pedido pedido) {
            this.AtualizarStatusPedidoAsync(pedido, null);
        }
        
        /// <remarks/>
        public void AtualizarStatusPedidoAsync(Pedido pedido, object userState) {
            if ((this.AtualizarStatusPedidoOperationCompleted == null)) {
                this.AtualizarStatusPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarStatusPedidoOperationCompleted);
            }
            this.InvokeAsync("AtualizarStatusPedido", new object[] {
                        pedido}, this.AtualizarStatusPedidoOperationCompleted, userState);
        }
        
        private void OnAtualizarStatusPedidoOperationCompleted(object arg) {
            if ((this.AtualizarStatusPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarStatusPedidoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ipt.br/soa")]
    public partial class Vinho {
        
        private int vinhoIdField;
        
        private string nomeField;
        
        private TipoVinho tipoField;
        
        private double precoField;
        
        private int prazoField;
        
        private int qtdeAtualField;
        
        private int qtdeMinimaField;
        
        /// <remarks/>
        public int vinhoId {
            get {
                return this.vinhoIdField;
            }
            set {
                this.vinhoIdField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public TipoVinho tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public double preco {
            get {
                return this.precoField;
            }
            set {
                this.precoField = value;
            }
        }
        
        /// <remarks/>
        public int prazo {
            get {
                return this.prazoField;
            }
            set {
                this.prazoField = value;
            }
        }
        
        /// <remarks/>
        public int qtdeAtual {
            get {
                return this.qtdeAtualField;
            }
            set {
                this.qtdeAtualField = value;
            }
        }
        
        /// <remarks/>
        public int qtdeMinima {
            get {
                return this.qtdeMinimaField;
            }
            set {
                this.qtdeMinimaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ipt.br/soa")]
    public enum TipoVinho {
        
        /// <remarks/>
        Branco,
        
        /// <remarks/>
        Tinto,
        
        /// <remarks/>
        Rose,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ipt.br/soa")]
    public partial class Pedido {
        
        private int pedidoIdField;
        
        private StatusPedido statusField;
        
        private System.DateTime dataField;
        
        private int qtdeTotalVinhoField;
        
        private double valorTotalField;
        
        private string cnpjField;
        
        private string cpfField;
        
        private string nomePFField;
        
        private string cartaoPFField;
        
        private string enderecoPFField;
        
        /// <remarks/>
        public int pedidoId {
            get {
                return this.pedidoIdField;
            }
            set {
                this.pedidoIdField = value;
            }
        }
        
        /// <remarks/>
        public StatusPedido status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public int qtdeTotalVinho {
            get {
                return this.qtdeTotalVinhoField;
            }
            set {
                this.qtdeTotalVinhoField = value;
            }
        }
        
        /// <remarks/>
        public double valorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string nomePF {
            get {
                return this.nomePFField;
            }
            set {
                this.nomePFField = value;
            }
        }
        
        /// <remarks/>
        public string cartaoPF {
            get {
                return this.cartaoPFField;
            }
            set {
                this.cartaoPFField = value;
            }
        }
        
        /// <remarks/>
        public string enderecoPF {
            get {
                return this.enderecoPFField;
            }
            set {
                this.enderecoPFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ipt.br/soa")]
    public enum StatusPedido {
        
        /// <remarks/>
        Estoque,
        
        /// <remarks/>
        Transito,
        
        /// <remarks/>
        Entregue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ipt.br/soa")]
    public partial class Reposicao {
        
        private int vinhoIdField;
        
        private string nomeField;
        
        private TipoVinho tipoField;
        
        private double precoField;
        
        private int qtdeAtualField;
        
        private int qtdeMinimaField;
        
        /// <remarks/>
        public int vinhoId {
            get {
                return this.vinhoIdField;
            }
            set {
                this.vinhoIdField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public TipoVinho tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public double preco {
            get {
                return this.precoField;
            }
            set {
                this.precoField = value;
            }
        }
        
        /// <remarks/>
        public int qtdeAtual {
            get {
                return this.qtdeAtualField;
            }
            set {
                this.qtdeAtualField = value;
            }
        }
        
        /// <remarks/>
        public int qtdeMinima {
            get {
                return this.qtdeMinimaField;
            }
            set {
                this.qtdeMinimaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ListarEstoqueCompletedEventHandler(object sender, ListarEstoqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEstoqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEstoqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vinho[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vinho[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void VerificarEstoqueCompletedEventHandler(object sender, VerificarEstoqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarEstoqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarEstoqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reposicao[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reposicao[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void VerificarDemandaCompletedEventHandler(object sender, VerificarDemandaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarDemandaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarDemandaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reposicao[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reposicao[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SolicitarReposicaoCompletedEventHandler(object sender, SolicitarReposicaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitarReposicaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitarReposicaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reposicao[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reposicao[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void EnviarArquivoXmlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void VerificarDataEntregaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void AtualizarStatusPedidoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591