//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace AdegaSOA.localhost5 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PedidoSoap", Namespace="http://ipt.br/soa")]
    public partial class Pedido : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarPedidosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GerarOrderIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarPedidoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Pedido() {
            this.Url = global::AdegaSOA.Properties.Settings.Default.AdegaSOA_localhost5_Pedido;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarPedidosCompletedEventHandler ListarPedidosCompleted;
        
        /// <remarks/>
        public event GerarOrderIdCompletedEventHandler GerarOrderIdCompleted;
        
        /// <remarks/>
        public event ConsultarPedidoCompletedEventHandler ConsultarPedidoCompleted;
        
        /// <remarks/>
        public event CancelarPedidoCompletedEventHandler CancelarPedidoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/ListarPedidos", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pedido1[] ListarPedidos() {
            object[] results = this.Invoke("ListarPedidos", new object[0]);
            return ((Pedido1[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPedidosAsync() {
            this.ListarPedidosAsync(null);
        }
        
        /// <remarks/>
        public void ListarPedidosAsync(object userState) {
            if ((this.ListarPedidosOperationCompleted == null)) {
                this.ListarPedidosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPedidosOperationCompleted);
            }
            this.InvokeAsync("ListarPedidos", new object[0], this.ListarPedidosOperationCompleted, userState);
        }
        
        private void OnListarPedidosOperationCompleted(object arg) {
            if ((this.ListarPedidosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPedidosCompleted(this, new ListarPedidosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/GerarOrderId", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pedido1 GerarOrderId(Venda venda) {
            object[] results = this.Invoke("GerarOrderId", new object[] {
                        venda});
            return ((Pedido1)(results[0]));
        }
        
        /// <remarks/>
        public void GerarOrderIdAsync(Venda venda) {
            this.GerarOrderIdAsync(venda, null);
        }
        
        /// <remarks/>
        public void GerarOrderIdAsync(Venda venda, object userState) {
            if ((this.GerarOrderIdOperationCompleted == null)) {
                this.GerarOrderIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGerarOrderIdOperationCompleted);
            }
            this.InvokeAsync("GerarOrderId", new object[] {
                        venda}, this.GerarOrderIdOperationCompleted, userState);
        }
        
        private void OnGerarOrderIdOperationCompleted(object arg) {
            if ((this.GerarOrderIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GerarOrderIdCompleted(this, new GerarOrderIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/ConsultarPedido", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pedido1 ConsultarPedido(int pedidoId) {
            object[] results = this.Invoke("ConsultarPedido", new object[] {
                        pedidoId});
            return ((Pedido1)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPedidoAsync(int pedidoId) {
            this.ConsultarPedidoAsync(pedidoId, null);
        }
        
        /// <remarks/>
        public void ConsultarPedidoAsync(int pedidoId, object userState) {
            if ((this.ConsultarPedidoOperationCompleted == null)) {
                this.ConsultarPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPedidoOperationCompleted);
            }
            this.InvokeAsync("ConsultarPedido", new object[] {
                        pedidoId}, this.ConsultarPedidoOperationCompleted, userState);
        }
        
        private void OnConsultarPedidoOperationCompleted(object arg) {
            if ((this.ConsultarPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPedidoCompleted(this, new ConsultarPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/CancelarPedido", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pedido1 CancelarPedido(Pedido1 pedido) {
            object[] results = this.Invoke("CancelarPedido", new object[] {
                        pedido});
            return ((Pedido1)(results[0]));
        }
        
        /// <remarks/>
        public void CancelarPedidoAsync(Pedido1 pedido) {
            this.CancelarPedidoAsync(pedido, null);
        }
        
        /// <remarks/>
        public void CancelarPedidoAsync(Pedido1 pedido, object userState) {
            if ((this.CancelarPedidoOperationCompleted == null)) {
                this.CancelarPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarPedidoOperationCompleted);
            }
            this.InvokeAsync("CancelarPedido", new object[] {
                        pedido}, this.CancelarPedidoOperationCompleted, userState);
        }
        
        private void OnCancelarPedidoOperationCompleted(object arg) {
            if ((this.CancelarPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarPedidoCompleted(this, new CancelarPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Pedido", Namespace="http://ipt.br/soa")]
    public partial class Pedido1 {
        
        private int pedidoIdField;
        
        private StatusPedido statusField;
        
        private System.DateTime dataField;
        
        private int qtdeTotalVinhoField;
        
        private double valorTotalField;
        
        private string cnpjField;
        
        private string cpfField;
        
        private string nomePFField;
        
        private string cartaoPFField;
        
        private string enderecoPFField;
        
        /// <remarks/>
        public int pedidoId {
            get {
                return this.pedidoIdField;
            }
            set {
                this.pedidoIdField = value;
            }
        }
        
        /// <remarks/>
        public StatusPedido status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public int qtdeTotalVinho {
            get {
                return this.qtdeTotalVinhoField;
            }
            set {
                this.qtdeTotalVinhoField = value;
            }
        }
        
        /// <remarks/>
        public double valorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string nomePF {
            get {
                return this.nomePFField;
            }
            set {
                this.nomePFField = value;
            }
        }
        
        /// <remarks/>
        public string cartaoPF {
            get {
                return this.cartaoPFField;
            }
            set {
                this.cartaoPFField = value;
            }
        }
        
        /// <remarks/>
        public string enderecoPF {
            get {
                return this.enderecoPFField;
            }
            set {
                this.enderecoPFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ipt.br/soa")]
    public enum StatusPedido {
        
        /// <remarks/>
        Estoque,
        
        /// <remarks/>
        Transito,
        
        /// <remarks/>
        Entregue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ipt.br/soa")]
    public partial class VinhoSelecionado {
        
        private int vinhoIdField;
        
        private int qtdeField;
        
        /// <remarks/>
        public int vinhoId {
            get {
                return this.vinhoIdField;
            }
            set {
                this.vinhoIdField = value;
            }
        }
        
        /// <remarks/>
        public int qtde {
            get {
                return this.qtdeField;
            }
            set {
                this.qtdeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ipt.br/soa")]
    public partial class Venda {
        
        private VinhoSelecionado[] vinhosField;
        
        private string cnpjField;
        
        private string cpfField;
        
        private string nomePFField;
        
        private string cartaoPFField;
        
        private string enderecoPFField;
        
        /// <remarks/>
        public VinhoSelecionado[] vinhos {
            get {
                return this.vinhosField;
            }
            set {
                this.vinhosField = value;
            }
        }
        
        /// <remarks/>
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string nomePF {
            get {
                return this.nomePFField;
            }
            set {
                this.nomePFField = value;
            }
        }
        
        /// <remarks/>
        public string cartaoPF {
            get {
                return this.cartaoPFField;
            }
            set {
                this.cartaoPFField = value;
            }
        }
        
        /// <remarks/>
        public string enderecoPF {
            get {
                return this.enderecoPFField;
            }
            set {
                this.enderecoPFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ListarPedidosCompletedEventHandler(object sender, ListarPedidosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPedidosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPedidosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pedido1[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pedido1[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GerarOrderIdCompletedEventHandler(object sender, GerarOrderIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GerarOrderIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GerarOrderIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pedido1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pedido1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ConsultarPedidoCompletedEventHandler(object sender, ConsultarPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pedido1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pedido1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CancelarPedidoCompletedEventHandler(object sender, CancelarPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelarPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelarPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pedido1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pedido1)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591