//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace AdegaSOA.localhost3 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CreditoSoap", Namespace="http://ipt.br/soa")]
    public partial class Credito : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DebitarCartaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreditarCartaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarSerasaSpcOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarSerasaSpcPJOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Credito() {
            this.Url = global::AdegaSOA.Properties.Settings.Default.AdegaSOA_localhost3_Credito;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DebitarCartaoCompletedEventHandler DebitarCartaoCompleted;
        
        /// <remarks/>
        public event CreditarCartaoCompletedEventHandler CreditarCartaoCompleted;
        
        /// <remarks/>
        public event ConsultarSerasaSpcCompletedEventHandler ConsultarSerasaSpcCompleted;
        
        /// <remarks/>
        public event ConsultarSerasaSpcPJCompletedEventHandler ConsultarSerasaSpcPJCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/DebitarCartao", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DebitarCartao(string cartaoId, double valor) {
            object[] results = this.Invoke("DebitarCartao", new object[] {
                        cartaoId,
                        valor});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DebitarCartaoAsync(string cartaoId, double valor) {
            this.DebitarCartaoAsync(cartaoId, valor, null);
        }
        
        /// <remarks/>
        public void DebitarCartaoAsync(string cartaoId, double valor, object userState) {
            if ((this.DebitarCartaoOperationCompleted == null)) {
                this.DebitarCartaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDebitarCartaoOperationCompleted);
            }
            this.InvokeAsync("DebitarCartao", new object[] {
                        cartaoId,
                        valor}, this.DebitarCartaoOperationCompleted, userState);
        }
        
        private void OnDebitarCartaoOperationCompleted(object arg) {
            if ((this.DebitarCartaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DebitarCartaoCompleted(this, new DebitarCartaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/CreditarCartao", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreditarCartao(string cartaoId, double valor) {
            this.Invoke("CreditarCartao", new object[] {
                        cartaoId,
                        valor});
        }
        
        /// <remarks/>
        public void CreditarCartaoAsync(string cartaoId, double valor) {
            this.CreditarCartaoAsync(cartaoId, valor, null);
        }
        
        /// <remarks/>
        public void CreditarCartaoAsync(string cartaoId, double valor, object userState) {
            if ((this.CreditarCartaoOperationCompleted == null)) {
                this.CreditarCartaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreditarCartaoOperationCompleted);
            }
            this.InvokeAsync("CreditarCartao", new object[] {
                        cartaoId,
                        valor}, this.CreditarCartaoOperationCompleted, userState);
        }
        
        private void OnCreditarCartaoOperationCompleted(object arg) {
            if ((this.CreditarCartaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreditarCartaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/ConsultarSerasaSpc", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ConsultarSerasaSpc(string cartaoId) {
            object[] results = this.Invoke("ConsultarSerasaSpc", new object[] {
                        cartaoId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarSerasaSpcAsync(string cartaoId) {
            this.ConsultarSerasaSpcAsync(cartaoId, null);
        }
        
        /// <remarks/>
        public void ConsultarSerasaSpcAsync(string cartaoId, object userState) {
            if ((this.ConsultarSerasaSpcOperationCompleted == null)) {
                this.ConsultarSerasaSpcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarSerasaSpcOperationCompleted);
            }
            this.InvokeAsync("ConsultarSerasaSpc", new object[] {
                        cartaoId}, this.ConsultarSerasaSpcOperationCompleted, userState);
        }
        
        private void OnConsultarSerasaSpcOperationCompleted(object arg) {
            if ((this.ConsultarSerasaSpcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarSerasaSpcCompleted(this, new ConsultarSerasaSpcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ipt.br/soa/ConsultarSerasaSpcPJ", RequestNamespace="http://ipt.br/soa", ResponseNamespace="http://ipt.br/soa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ConsultarSerasaSpcPJ(string cnpj) {
            object[] results = this.Invoke("ConsultarSerasaSpcPJ", new object[] {
                        cnpj});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarSerasaSpcPJAsync(string cnpj) {
            this.ConsultarSerasaSpcPJAsync(cnpj, null);
        }
        
        /// <remarks/>
        public void ConsultarSerasaSpcPJAsync(string cnpj, object userState) {
            if ((this.ConsultarSerasaSpcPJOperationCompleted == null)) {
                this.ConsultarSerasaSpcPJOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarSerasaSpcPJOperationCompleted);
            }
            this.InvokeAsync("ConsultarSerasaSpcPJ", new object[] {
                        cnpj}, this.ConsultarSerasaSpcPJOperationCompleted, userState);
        }
        
        private void OnConsultarSerasaSpcPJOperationCompleted(object arg) {
            if ((this.ConsultarSerasaSpcPJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarSerasaSpcPJCompleted(this, new ConsultarSerasaSpcPJCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void DebitarCartaoCompletedEventHandler(object sender, DebitarCartaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DebitarCartaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DebitarCartaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CreditarCartaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ConsultarSerasaSpcCompletedEventHandler(object sender, ConsultarSerasaSpcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarSerasaSpcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarSerasaSpcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ConsultarSerasaSpcPJCompletedEventHandler(object sender, ConsultarSerasaSpcPJCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarSerasaSpcPJCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarSerasaSpcPJCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591